services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password_Pro_2026!
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql

  api:
    build: ./backend
    container_name: ruby_api
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PASSWORD=Password_Pro_2026!
